name: Pylint

# Trigger on push or pull request to main and any other branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: List all Python files
        run: |
          find . -name "*.py"
      - name: Analyzing the code with pylint
        run: |
          find $(pwd) -name "*.py" | while read file; do
            pylint --rcfile=$(pwd)/.pylintrc "$file" || exit_code=$?
          done
          exit ${exit_code:-0}
        continue-on-error: false
        
        
        
        
